config/routes.rb
Rails.application.routes.draw do
  root 'regions#index'

  resources :regions, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :region
end

app/models/region.rb
class Region < ApplicationRecord
  has_many :houses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController
  def index
    @regions = Region.all
  end

  def show
    @region = Region.find(params[:id])
    @houses = @region.houses
    key = ENV["DARK_SKY_KEY"]
    weather = HTTParty.get("https://api.darksky.net/forecast/#{key}/#{@region.latitude},#{@region.longitude}")
    @region.update_attributes({ weather: weather['currently']['summary'], temperature: weather['currently']['temperature'] })
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ApiGotGeography</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/regions/index.html.erb
<div class='regions'>
  <h1>Regions of Westeros</h1>
  <% @regions.each do |region| %>
    <li><%= link_to region.name, region_path(region) %></li>
  <% end %>
</div>

app/views/regions/show.html.erb
<div class="regions">
  <h1><%= @region.name %></h1>

  <p>Climate: <%= @region.weather %></p>
  <p>Current Temp: <%= @region.temperature %></p>
  <h2>Houses:</h2>
  <% @houses.each do |house| %>
  <h3><%= house.name %></h3>
  <li>Sigil: <%= house.sigil %></li>
  <% if house.words %>
  <li>House Words: <%= house.words %></li>
  <% end %>
  <% end %>
</div>